import os
import re
import json
import requests
from pathlib import Path


COMMENT_COMPONENT_RE = re.compile(r"CB_COMPONENT:\s*([A-Za-z0-9._-]+)")
COMMENT_SCOPE_RE = re.compile(r"CB_SCOPE:\s*([A-Za-z0-9_./-]+)")
FUNC_RE = re.compile(
    r"""^\s*
    (?:[A-Za-z_][A-Za-z0-9_\s\*\(\),]*\s+)?   # return type
    ([A-Za-z_][A-Za-z0-9_]*)                  # function name
    \s*\([^;]*\)\s*\{                         # (...) {
    """,
    re.VERBOSE,
)


def find_target_comment_and_function(repo_root: Path):
    """
    저장소 전체에서 첫 번째 CB_COMPONENT/CB_SCOPE 주석 쌍을 찾고,
    그 아래 첫 함수의 시작/끝 줄을 계산합니다.
    """
    for file_path in repo_root.rglob("*"):
        if not file_path.is_file():
            continue
        if file_path.suffix.lower() not in {".c", ".cpp", ".cc", ".h", ".hpp", ".java"}:
            continue

        text = file_path.read_text(encoding="utf-8", errors="ignore")
        lines = text.splitlines()

        for i in range(len(lines) - 1):
            block = lines[i] + "\n" + lines[i + 1]
            component_match = COMMENT_COMPONENT_RE.search(block)
            scope_match = COMMENT_SCOPE_RE.search(block)

            if not component_match or not scope_match:
                continue

            component_key = component_match.group(1).strip()
            scope_name = scope_match.group(1).strip()

            # 주석 다음 함수 찾기
            func_start = None
            brace_balance = 0
            func_end = None

            for j in range(i + 1, len(lines)):
                if func_start is None and FUNC_RE.search(lines[j]):
                    func_start = j + 1  # 1-based line number
                    brace_balance += lines[j].count("{") - lines[j].count("}")
                    if brace_balance == 0:
                        func_end = func_start
                        break
                    continue

                if func_start is not None:
                    brace_balance += lines[j].count("{") - lines[j].count("}")
                    if brace_balance == 0:
                        func_end = j + 1
                        break

            if func_start and func_end:
                relative_path = file_path.relative_to(repo_root).as_posix()
                return {
                    "component_key": component_key,
                    "scope_name": scope_name,
                    "file_path": relative_path,
                    "start_line": func_start,
                    "end_line": func_end,
                }

    raise RuntimeError("CB_COMPONENT / CB_SCOPE 주석 쌍을 찾지 못했습니다.")


def build_permalink(server_url: str, repository: str, sha: str, file_path: str, start_line: int, end_line: int) -> str:
    return f"{server_url}/{repository}/blob/{sha}/{file_path}#L{start_line}-L{end_line}"


def create_codebeamer_item(data: dict):
    base_url = os.environ["CB_BASE_URL"].rstrip("/")
    username = os.environ["CB_USERNAME"]
    password = os.environ["CB_PASSWORD"]
    tracker_id = os.environ["CB_TRACKER_ID"]

    # field IDs
    field_repository = int(os.environ["CB_FIELD_REPOSITORY"])
    field_file_path = int(os.environ["CB_FIELD_FILE_PATH"])
    field_start_line = int(os.environ["CB_FIELD_START_LINE"])
    field_end_line = int(os.environ["CB_FIELD_END_LINE"])
    field_scope_name = int(os.environ["CB_FIELD_SCOPE_NAME"])
    field_commit_sha = int(os.environ["CB_FIELD_COMMIT_SHA"])
    field_permalink = int(os.environ["CB_FIELD_PERMALINK"])
    field_linked_component = int(os.environ["CB_FIELD_LINKED_COMPONENT"])

    # 이 예시는 component item id를 secret으로 직접 넣는 최소 예시
    component_item_id = int(os.environ["CB_COMPONENT_ITEM_ID"])

    payload = {
        "name": f'{data["scope_name"]} @ {data["file_path"]}',
        "description": "Generated by GitHub Actions",
        "descriptionFormat": "PlainText",
        "customFields": [
            {
                "fieldId": field_repository,
                "name": "Repository Name",
                "value": data["repository"],
                "type": "TextFieldValue",
            },
            {
                "fieldId": field_file_path,
                "name": "File Path",
                "value": data["file_path"],
                "type": "TextFieldValue",
            },
            {
                "fieldId": field_start_line,
                "name": "Start Line",
                "value": data["start_line"],
                "type": "IntegerFieldValue",
            },
            {
                "fieldId": field_end_line,
                "name": "End Line",
                "value": data["end_line"],
                "type": "IntegerFieldValue",
            },
            {
                "fieldId": field_scope_name,
                "name": "Scope Name",
                "value": data["scope_name"],
                "type": "TextFieldValue",
            },
            {
                "fieldId": field_commit_sha,
                "name": "Commit SHA",
                "value": data["commit_sha"],
                "type": "TextFieldValue",
            },
            {
                "fieldId": field_permalink,
                "name": "GitHub Permalink",
                "value": data["permalink"],
                "type": "TextFieldValue",
            },
            {
                "fieldId": field_linked_component,
                "name": "Linked Component",
                "type": "ChoiceFieldValue",
                "values": [
                    {
                        "id": component_item_id,
                        "name": data["component_key"],
                        "type": "TrackerItemReference",
                    }
                ],
            },
        ],
    }

    url = f"{base_url}/v3/trackers/{tracker_id}/items"
    resp = requests.post(url, auth=(username, password), json=payload, timeout=60)
    resp.raise_for_status()

    print("Created Codebeamer item successfully.")
    print(json.dumps(resp.json(), indent=2, ensure_ascii=False))


def main():
    repo_root = Path(".").resolve()

    found = find_target_comment_and_function(repo_root)

    server_url = os.environ["GITHUB_SERVER_URL"]
    repository = os.environ["GITHUB_REPOSITORY"]
    sha = os.environ["GITHUB_SHA"]

    permalink = build_permalink(
        server_url=server_url,
        repository=repository,
        sha=sha,
        file_path=found["file_path"],
        start_line=found["start_line"],
        end_line=found["end_line"],
    )

    payload_data = {
        "component_key": found["component_key"],
        "scope_name": found["scope_name"],
        "file_path": found["file_path"],
        "start_line": found["start_line"],
        "end_line": found["end_line"],
        "repository": repository,
        "commit_sha": sha,
        "permalink": permalink,
    }

    print("Parsed data:")
    print(json.dumps(payload_data, indent=2, ensure_ascii=False))

    create_codebeamer_item(payload_data)


if __name__ == "__main__":
    main()
