name: Sync Code Evidence

on:
 workflow_dispatch:
 push:
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Create Codebeamer item from one comment
        env:
          CB_BASE_URL: http://cbcnbis.com:8080
          CB_USERNAME: admin
          CB_PASSWORD: Cnbis123!
          CB_TRACKER_ID: 146182
          CB_COMPONENT_TRACKER_ID: 122808

          CB_FIELD_REPOSITORY: ${{ secrets.CB_FIELD_REPOSITORY }}
          CB_FIELD_FILE_PATH: ${{ secrets.CB_FIELD_FILE_PATH }}
          CB_FIELD_START_LINE: ${{ secrets.CB_FIELD_START_LINE }}
          CB_FIELD_END_LINE: ${{ secrets.CB_FIELD_END_LINE }}
          CB_FIELD_SCOPE_NAME: ${{ secrets.CB_FIELD_SCOPE_NAME }}
          CB_FIELD_COMMIT_SHA: ${{ secrets.CB_FIELD_COMMIT_SHA }}
          CB_FIELD_PERMALINK: ${{ secrets.CB_FIELD_PERMALINK }}
          CB_FIELD_LINKED_COMPONENT: ${{ secrets.CB_FIELD_LINKED_COMPONENT }}

          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: python scripts/sync_code_evidence.py
