name: Sync Code Evidence

on:
 workflow_dispatch:
 push:
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Create Codebeamer item from one comment
        env:
          CB_BASE_URL: http://218.237.27.234:8080/cb
          CB_USERNAME: admin
          CB_PASSWORD: Cnbis123!
          CB_TRACKER_ID: 146182
          CB_COMPONENT_TRACKER_ID: 122808

          CB_FIELD_REPOSITORY: 3
          CB_FIELD_FILE_PATH: 10001
          CB_FIELD_START_LINE: 10002
          CB_FIELD_END_LINE: 10003
          CB_FIELD_SCOPE_NAME: 10004
          CB_FIELD_COMMIT_SHA: 10005
          CB_FIELD_PERMALINK: 10006
          CB_FIELD_LINKED_COMPONENT: 1002
          
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: python scripts/sync_code_evidence.py
